intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

lib{patterns}: {hxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base/include"

# Export options.
#
lib{patterns}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base/include"
  cxx.export.libs = $intf_libs
}

# Install into the patterns/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx}{*}:
{
  install         = include/
  install.subdirs = true
}
